---
title: "Farm accounts in the regions of England"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
if(!require(pacman)) {
  install.packages('pacman')
  library(pacman)
}

#load other packages
p_load(tidyverse, 
       glue, 
       fs, 
       readxl, 
       cli,
       scales,
       gridExtra,
       knitr,
       lubridate,
       janitor,
       here,
       ggfbs,
       xlsx,
       snakecase,
       plotly)

library(flexdashboard)

working_year <- 2021
previous_year <- 2020

source(here('Dashboard fun', 'scripts', 'prep_data_regional.R'))
source(here('Dashboard fun', 'scripts', 'functions_regional.R'))
source(here('Dashboard fun', 'scripts', 'figure_maker_each_region.R'))
source(here('Dashboard fun', 'scripts', 'map_of_regions.R'))
```

Home page
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Intro and use

This publication contains the summary of the farm accounts in the regions of England for 2021 and will address trends for the ITL1 regions, this has been published alongside more detailed data sets for each of the respective ITL1 regions which further breaks down the data to ITL2 level.

Total Income from Farming (TIFF) is the income to those who own businesses within the agricultural industry. It is the total profit from all UK farming businesses on a calendar year basis. It measures the return to all entrepreneurs for their management, inputs, labour and capital invested. The term ‘income’ used throughout this notice refers to TIFF.

### User feedback

We want to improve our understanding of how people use our TIFF publications and how we can improve them to better meet user needs. Please take the time to complete a short feedback form to help us better understand user needs. 

[User feedback form](https://docs.google.com/forms/d/1f0lVRIF5tqWKsqGCX_eyj7QqAyF0fo99YQUPbUwdFnU/edit)

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

``` {r, child = "North East.Rmd"}
```