North East
================================================================================

```{r include = FALSE}
regional_code <- "UKC"

regional_data <- ukc
```


Column {data-width = 350}
--------------------------------------------------------------------------------

```{r, include = FALSE}
itl1_region_map <- itl1_map_highlight(regional_code)
itl3_region_map <- itl3_map_highlight(regional_code)

plot1 <- ggplot()+
  geom_sf(data = eng_nuts1, fill = "NA", colour = "#0b0c0c", size = 0.7) +
  geom_sf(data = itl1_region_map, fill = "#12436d", size = 0.7) +
  theme_void()

plot2 <- ggplot()+
  geom_sf(data = itl3_region_map, fill = "#12436d", colour = "#0b0c0c", size = 1) +
  labs(caption = ("Source: Defra \u00A9 Crown copyright")) +
  theme_void()+
  theme(plot.caption = element_text(size = 16, family = "GDS Transport Website"))
```

### Region within the UK

```{r}
grid.arrange(plot1, plot2, ncol = 2)
```

### Outputs and subsidies

```{r}
ggplotly(itl1_outputs_and_subsidies_years_function(regional_data))
```

***

* Total livestock output has made the biggest contribution to outputs and subsidies
in the North East in 6  out of the past 6 years, contributing at least 
41.6%. In 2021 Total livestock output contributed 
45.2% of the £882 million of 
outputs and subsidies, the 3rd highest proportion of the past 6 years.

* Direct payments have made up between 15.4% and 19.6% of the total 
outputs and subsidies in the past 6 years for the North East. In 2021, direct payments 
made up 15.4% of total outputs and subsidies.


Column {data-width = 650}
--------------------------------------------------------------------------------

### TIFF
```{r}
ggplotly(itl1_tiff_years_function(regional_data))
```

* TIFF in the North East in 2021 was £190 million, an increase of £36 
million (23%) from 2020.

* In 2021 TIFF in the North East was at its highest value in the last 6 years.